"""
Django settings for WowDash project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse, parse_qs

# Cargar variables desde .env si existe (solo local); en producciÃ³n Render usa env vars del servicio
try:
    from dotenv import load_dotenv  # type: ignore
    # Paths de posibles .env (ambos aceptados):
    # - Django/.env (junto a manage.py)
    # - RaÃ­z del repositorio /.env
    _DOTENV_ROOT = Path(__file__).resolve().parents[2] / '.env'      # repo-root/.env
    _DOTENV_DJANGO = Path(__file__).resolve().parent.parent / '.env' # Django/.env
    # Cargar primero el de la raÃ­z (sin override) y luego el de Django (con override=True)
    if _DOTENV_ROOT.exists():
        load_dotenv(dotenv_path=_DOTENV_ROOT, override=False)
    if _DOTENV_DJANGO.exists():
        load_dotenv(dotenv_path=_DOTENV_DJANGO, override=True)
except Exception:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY: claves/flags desde variables de entorno en producciÃ³n
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-y9+u@w))$2g_mqgif#vknt$reo$o!p#h3!r4gyq!=i4s!#cxiw')
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'y')
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if not DEBUG else ['*']

# CSRF trusted origins: leer desde variable de entorno (por ejemplo en Codespaces)
# Valor esperado: una lista separada por comas de orÃ­genes completos, p.ej.
# https://special-adventure-...-8000.app.github.dev,https://localhost:8000
csrf_env = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if csrf_env:
    CSRF_TRUSTED_ORIGINS = [x.strip() for x in csrf_env.split(',') if x.strip()]
else:
    # En desarrollo, permitir orÃ­genes locales comunes (http y https; puertos 8000/8001)
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000', 'https://localhost:8000',
        'http://localhost:8001', 'https://localhost:8001',
        'http://127.0.0.1:8000', 'https://127.0.0.1:8000',
        'http://127.0.0.1:8001', 'https://127.0.0.1:8001',
    ]
    # Si se estÃ¡ ejecutando en Codespaces, agregar el dominio de reenvÃ­o de puertos
    cname = os.getenv('CODESPACE_NAME')
    cdomain = os.getenv('GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN')
    if cname and cdomain:
        # Ej.: https://<codespace>-8001.<domain>
        CSRF_TRUSTED_ORIGINS += [
            f"https://{cname}-8000.{cdomain}",
            f"https://{cname}-8001.{cdomain}",
        ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',  # AplicaciÃ³n principal del sistema Optimizador
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise para servir estÃ¡ticos en producciÃ³n
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'WowDash.middleware.RequireLoginMiddleware',
    'WowDash.middleware.NoCacheMiddleware',
    # Middleware para exponer la request/usuario actual a seÃ±ales (audit)
    'core.middleware.RequestUserMiddleware',
    # Aislar flujo de autoservicio
    'core.middleware.AutoServicioIsolationMiddleware',
]

ROOT_URLCONF = 'WowDash.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # Registrar librerÃ­as de template personalizadas
            'libraries': {
                'ui_extras': 'core.templatetags.ui_extras',
            },
        },
    },
]

WSGI_APPLICATION = 'WowDash.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Forzar SQLite en desarrollo si se define DJANGO_USE_SQLITE=1 (ignora DATABASE_URL/DB_*)
if os.getenv('DJANGO_USE_SQLITE', '').lower() in ('1', 'true', 'yes', 'y'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    database_url = os.getenv('DATABASE_URL')
    if database_url:
        # Espera formato postgres://USER:PASSWORD@HOST:PORT/NAME?sslmode=require
        parsed = urlparse(database_url)
        query = parse_qs(parsed.query)
        db_conf = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path.lstrip('/'),
            'USER': parsed.username,
            'PASSWORD': parsed.password,
            'HOST': parsed.hostname,
            'PORT': str(parsed.port or ''),
        }
        # Pasar opciones como sslmode a psycopg2; si no viene, forzar 'require' en producciÃ³n
        # Opciones de conexiÃ³n (SSL + keepalives para evitar resets por inactividad)
        if 'sslmode' in query:
            sslmode = query['sslmode'][0]
        else:
            sslmode = 'require' if not DEBUG else query.get('sslmode', ['prefer'])[0]
        db_conf['OPTIONS'] = {
            'sslmode': sslmode,
            # Keepalive tuning (psycopg2) para conexiones estables en Render/hosts remotos
            'keepalives': 1,
            'keepalives_idle': int(os.getenv('DB_KEEPALIVES_IDLE', '60')),
            'keepalives_interval': int(os.getenv('DB_KEEPALIVES_INTERVAL', '15')),
            'keepalives_count': int(os.getenv('DB_KEEPALIVES_COUNT', '5')),
        }
        DATABASES = {'default': db_conf}
    else:
        # Si existen variables individuales de conexiÃ³n, usar PostgreSQL
        db_name = os.getenv('DB_NAME')
        db_user = os.getenv('DB_USER')
        db_password = os.getenv('DB_PASSWORD')
        db_host = os.getenv('DB_HOST')
        db_port = os.getenv('DB_PORT', '5432')
        if all([db_name, db_user, db_password, db_host]):
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': db_name,
                    'USER': db_user,
                    'PASSWORD': db_password,
                    'HOST': db_host,
                    'PORT': db_port,
                    'OPTIONS': {
                        'sslmode': os.getenv('DB_SSLMODE', 'require' if not DEBUG else 'prefer'),
                        'keepalives': 1,
                        'keepalives_idle': int(os.getenv('DB_KEEPALIVES_IDLE', '60')),
                        'keepalives_interval': int(os.getenv('DB_KEEPALIVES_INTERVAL', '15')),
                        'keepalives_count': int(os.getenv('DB_KEEPALIVES_COUNT', '5')),
                    }
                }
            }
        else:
            # Desarrollo local por defecto: SQLite (usa el db.sqlite3 existente)
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': BASE_DIR / 'db.sqlite3',
                }
            }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Idiomas disponibles
LANGUAGES = [
    ('es', 'EspaÃ±ol'),
    ('en', 'English'),
]

# Directorio de traducciones
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Si se define una URL externa (Render), usa esa para servir estÃ¡ticos
RENDER_EXTERNAL_URL = os.getenv('RENDER_EXTERNAL_URL')
if RENDER_EXTERNAL_URL and not DEBUG:
    STATIC_URL = RENDER_EXTERNAL_URL.rstrip('/') + '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# WhiteNoise: permitir archivos estÃ¡ticos comprimidos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Authentication settings
LOGIN_URL = '/authentication/signin/'
LOGIN_REDIRECT_URL = '/proyectos/'
LOGOUT_REDIRECT_URL = '/authentication/signin/'

# Session settings: cerrar sesiÃ³n al cerrar navegador y expirar por inactividad
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# 30 minutos (en segundos)
SESSION_COOKIE_AGE = 30 * 60
# Renueva el vencimiento con cada request (actividad)
SESSION_SAVE_EVERY_REQUEST = True

# Media files (user-generated content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Persistencia de conexiÃ³n DB: reutiliza conexiones y realiza health checks para evitar errores
CONN_MAX_AGE = int(os.getenv('DB_CONN_MAX_AGE', '300'))  # segundos
CONN_HEALTH_CHECKS = True  # Django >=4.2