# Generated by Django 5.2.7 on 2025-10-15 08:41

import django.db.models.deletion
from django.db import migrations, models


def fix_ancho_mayor(apps, schema_editor):
    Material = apps.get_model('core', 'Material')
    for m in Material.objects.all():
        if m.largo and m.ancho and m.largo > m.ancho:
            a, b = m.ancho, m.largo
            m.ancho, m.largo = b, a
            m.save(update_fields=['ancho', 'largo'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='tapacanto',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='tapacanto',
            name='precio_metro',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por metro'),
        ),
        migrations.AlterField(
            model_name='usuarioperfiloptimizador',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('org_admin', 'Administrador de Organización'), ('agente', 'Agente')], default='agente', max_length=20, verbose_name='Rol'),
        ),
        migrations.RunPython(fix_ancho_mayor, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('ancho__gte', models.F('largo'))), name='material_ancho_mayor_igual_largo'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('ancho__gt', 0), ('largo__gt', 0)), name='material_dimensiones_positivas'),
        ),
    ]
