# Generated by Django 4.2.27 on 2026-03-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cliente_rut_alter_usuarioperfiloptimizador_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En Proceso'), ('optimizado', 'Optimizado'), ('aprobado', 'Aprobado'), ('produccion', 'En Producción'), ('enchapado_pendiente', 'Enchapado Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuarioperfiloptimizador',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('org_admin', 'Administrador de Organización'), ('agente', 'Agente'), ('subordinador', 'Subordinador'), ('operador', 'Operador'), ('enchapador', 'Enchapador'), ('supervisor', 'Supervisor'), ('autoservicio', 'Autoservicio')], default='agente', max_length=20, verbose_name='Rol'),
        ),
    ]
