# Generated by Django 4.2.27 on 2026-03-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_enchapador_role_and_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En Proceso'), ('optimizado', 'Optimizado'), ('aprobado', 'Aprobado'), ('asignado', 'Asignado'), ('produccion', 'En Producción'), ('enchapado_pendiente', 'Enchapado Pendiente'), ('completado', 'Completado'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
