# Generated by Django 4.2.27 on 2026-03-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_notificacionenchapador'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['organizacion', 'estado', 'fecha_creacion'], name='proy_org_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['operador', 'estado'], name='proy_operador_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['estado'], name='proy_estado_idx'),
        ),
    ]
