# Generated by Django 4.2.27 on 2026-03-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_proyecto_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfiloptimizador',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('org_admin', 'Administrador de Organización'), ('vendedor', 'Vendedor'), ('subordinador', 'Subordinador'), ('operador', 'Operador'), ('enchapador', 'Enchapador'), ('supervisor', 'Supervisor'), ('autoservicio', 'Autoservicio')], default='vendedor', max_length=20, verbose_name='Rol'),
        ),
    ]
