# Generated by Django 4.2.27 on 2026-03-26 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_data_agente_to_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminSatelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20, verbose_name='Rol del Satélite')),
                ('satelite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satelite_de', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Satélite')),
                ('super_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satelites_propios', to=settings.AUTH_USER_MODEL, verbose_name='Super Admin')),
            ],
            options={
                'verbose_name': 'Satélite Super Admin',
                'verbose_name_plural': 'Satélites Super Admin',
                'unique_together': {('super_admin', 'rol')},
            },
        ),
    ]
