# Generated by Django 4.2.27 on 2026-03-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_superadmin_satelite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho_mm', models.PositiveIntegerField(default=70, verbose_name='Ancho etiqueta (mm)')),
                ('alto_mm', models.PositiveIntegerField(default=50, verbose_name='Alto etiqueta (mm)')),
                ('mostrar_nombre', models.BooleanField(default=True, verbose_name='Mostrar nombre de pieza')),
                ('mostrar_material', models.BooleanField(default=True, verbose_name='Mostrar material')),
                ('mostrar_cliente', models.BooleanField(default=False, verbose_name='Mostrar cliente')),
                ('mostrar_proyecto_id', models.BooleanField(default=False, verbose_name='Mostrar ID proyecto')),
                ('mostrar_dibujo', models.BooleanField(default=True, verbose_name='Mostrar dibujo de pieza')),
                ('mostrar_cotas', models.BooleanField(default=True, verbose_name='Mostrar cotas (medidas)')),
                ('mostrar_tapacantos', models.BooleanField(default=True, verbose_name='Mostrar tapacantos')),
                ('mostrar_veta', models.BooleanField(default=True, verbose_name='Mostrar dirección de veta')),
                ('fuente_nombre', models.PositiveIntegerField(default=32, help_text='Tamaño de fuente del nombre. 24=pequeño, 32=medio, 48=grande, 64=muy grande', verbose_name='Fuente nombre (dots)')),
                ('fuente_material', models.PositiveIntegerField(default=24, verbose_name='Fuente material (dots)')),
                ('fuente_cotas', models.PositiveIntegerField(default=22, verbose_name='Fuente cotas (dots)')),
                ('fuente_pie', models.PositiveIntegerField(default=22, help_text='Fuente para la línea de tapacantos y veta', verbose_name='Fuente pie (dots)')),
                ('escala_dibujo', models.FloatField(default=0.75, help_text='0.5 = pequeño, 0.75 = medio, 1.0 = grande', verbose_name='Escala del dibujo')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('organizacion', models.OneToOneField(blank=True, help_text='Dejar vacío para configuración global por defecto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_etiqueta', to='core.organizacion', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Configuración de etiqueta',
                'verbose_name_plural': 'Configuraciones de etiqueta',
            },
        ),
    ]
