# Generated by Django 4.2.27 on 2026-03-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_configuracion_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionetiqueta',
            name='posiciones',
            field=models.JSONField(blank=True, default=dict, help_text='JSON con las posiciones x,y de cada campo en la etiqueta (en % relativo)', verbose_name='Posiciones de elementos'),
        ),
    ]
