# Generated by Django 4.2.27 on 2026-03-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_etiqueta_posiciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionetiqueta',
            name='fuente_cliente',
            field=models.PositiveIntegerField(default=20, verbose_name='Fuente cliente (dots)'),
        ),
        migrations.AddField(
            model_name='configuracionetiqueta',
            name='fuente_proyecto_id',
            field=models.PositiveIntegerField(default=20, verbose_name='Fuente ID proyecto (dots)'),
        ),
        migrations.AddField(
            model_name='configuracionetiqueta',
            name='grosor_borde',
            field=models.PositiveIntegerField(default=2, help_text='Grosor de la línea del rectángulo de la pieza. 1=fino, 2=normal, 4=grueso, 6=muy grueso', verbose_name='Grosor borde figura (dots)'),
        ),
    ]
