# Generated by Django 4.2.27 on 2026-04-01 00:11

from django.db import migrations


def forwards(apps, schema_editor):
    """Renombrar el valor 'subordinador' → 'subordinado' en perfiles existentes."""
    UsuarioPerfilOptimizador = apps.get_model('core', 'UsuarioPerfilOptimizador')
    updated = UsuarioPerfilOptimizador.objects.filter(rol='subordinador').update(rol='subordinado')
    print(f'  Migración: {updated} perfil(es) renombrado(s) subordinador → subordinado')


def backwards(apps, schema_editor):
    """Revertir: subordinado → subordinador"""
    UsuarioPerfilOptimizador = apps.get_model('core', 'UsuarioPerfilOptimizador')
    UsuarioPerfilOptimizador.objects.filter(rol='subordinado').update(rol='subordinador')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_etiqueta_fuentes_grosor'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
